[package]
name = "thinkpadfan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
wayland-client = "0.30.1"
winit = "0.28.3"
